AWSTemplateFormatVersion: 2010-09-09
Description: Build an EC2 Instance with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03d5c68bab01f3496
      InstanceType: t2.micro