AWSTemplateFormatVersion: 2010-09-09
Description: Build an ECS Cluster with AWS CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: [
            "FARGATE",
            "FARGATE_SPOT"
        ]
      ClusterName: pradipta-ecs-cluster-cloudformation
      ClusterSettings: 
           - Name: containerInsights
             Value: enabled
      Configuration:
       ExecuteCommandConfiguration:
          Logging: DEFAULT

      DefaultCapacityProviderStrategy: [
            {
                "CapacityProvider": "FARGATE",
                "Weight": 1
            },
            {
                "CapacityProvider": "FARGATE_SPOT",
                "Weight": 1
            }
        ]
      Tags: [ { "Key" : "Environment", "Value" : "Dev" } ]