version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    parameters:
      stack-name:
        description: Name of the CloudFormation stack
        type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Cloudformation Template with new Docker image
          command: aws cloudformation create-stack --stack-name pradipta-ec2-cloudformation --template-body file://ec2.yml        

workflows:
  deploy_infrastructure:
    jobs:
      - deploy-cfn:
          context: aws-cloudformation
          stack-name: pradipta-ec2-cloudformation